export const data = {
  "articles": {
    id: 1,
    title: "Articles",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam nibh at tortor ullamcorper efficitur. In eu facilisis quam. Proin velit nulla, pulvinar aliquet pharetra eget, dictum volutpat eros. Sed sit amet nisi nisl. Pellentesque ac enim suscipit, congue erat in, congue elit. Nam iaculis dolor et est cursus varius. Suspendisse potenti. Nunc ut scelerisque tortor, a commodo neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis a arcu at risus laoreet molestie. Etiam tortor libero, feugiat quis ante a, cursus sagittis risus. Morbi hendrerit dolor vitae justo porta tempor. Integer sit amet mi vel nulla molestie posuere. Curabitur et elementum ipsum. Quisque eget felis ac neque dictum euismod.",
    page_type_id: 2,
    headline_id: 1,
    map_box_id: null,
  },
  "about": {
    id: 2,
    title: "About",
    content: "Vestibulum at ligula at nunc egestas vehicula sit amet et velit. Integer varius, justo eu volutpat congue, neque ante scelerisque nulla, id volutpat sem leo in nibh. Vestibulum auctor diam a turpis fringilla feugiat. Nam lacinia convallis velit quis tincidunt. Duis vestibulum tincidunt mollis. Phasellus efficitur suscipit ultricies. Morbi quis fringilla lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, nulla sed posuere euismod, orci mauris cursus ligula, ut maximus arcu erat a nibh. Morbi quis mollis velit, imperdiet convallis sapien. Vivamus fringilla venenatis vulputate. Maecenas vitae magna non est tristique sodales. Pellentesque iaculis a felis accumsan tempus. Vestibulum fringilla efficitur metus, nec condimentum ipsum auctor non. Vestibulum sed orci ac augue congue porttitor a sed lorem. Sed dolor justo, ultrices in placerat at, gravida sit amet dolor.",
    page_type_id: 1,
    headline_id: 2,
    map_box_id: null,
  },
  "expertise": {
    id: 3,
    title: "Expertise",
    content: "Vestibulum at ligula at nunc egestas vehicula sit amet et velit. Integer varius, justo eu volutpat congue, neque ante scelerisque nulla, id volutpat sem leo in nibh. Vestibulum auctor diam a turpis fringilla feugiat. Nam lacinia convallis velit quis tincidunt. Duis vestibulum tincidunt mollis. Phasellus efficitur suscipit ultricies. Morbi quis fringilla lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, nulla sed posuere euismod, orci mauris cursus ligula, ut maximus arcu erat a nibh. Morbi quis mollis velit, imperdiet convallis sapien. Vivamus fringilla venenatis vulputate. Maecenas vitae magna non est tristique sodales. Pellentesque iaculis a felis accumsan tempus. Vestibulum fringilla efficitur metus, nec condimentum ipsum auctor non. Vestibulum sed orci ac augue congue porttitor a sed lorem. Sed dolor justo, ultrices in placerat at, gravida sit amet dolor.",
    page_type_id: 1,
    headline_id: 3,
    map_box_id: null,
  },
  "people-say": {
    id: 4,
    title: "People say",
    content: "Vestibulum at ligula at nunc egestas vehicula sit amet et velit. Integer varius, justo eu volutpat congue, neque ante scelerisque nulla, id volutpat sem leo in nibh. Vestibulum auctor diam a turpis fringilla feugiat. Nam lacinia convallis velit quis tincidunt. Duis vestibulum tincidunt mollis. Phasellus efficitur suscipit ultricies. Morbi quis fringilla lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, nulla sed posuere euismod, orci mauris cursus ligula, ut maximus arcu erat a nibh. Morbi quis mollis velit, imperdiet convallis sapien. Vivamus fringilla venenatis vulputate. Maecenas vitae magna non est tristique sodales. Pellentesque iaculis a felis accumsan tempus. Vestibulum fringilla efficitur metus, nec condimentum ipsum auctor non. Vestibulum sed orci ac augue congue porttitor a sed lorem. Sed dolor justo, ultrices in placerat at, gravida sit amet dolor.",
    page_type_id: 1,
    headline_id: 4,
    map_box_id: null,
  },
  "works": {
    id: 5,
    title: "Works",
    content: "Vestibulum at ligula at nunc egestas vehicula sit amet et velit. Integer varius, justo eu volutpat congue, neque ante scelerisque nulla, id volutpat sem leo in nibh. Vestibulum auctor diam a turpis fringilla feugiat. Nam lacinia convallis velit quis tincidunt. Duis vestibulum tincidunt mollis. Phasellus efficitur suscipit ultricies. Morbi quis fringilla lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, nulla sed posuere euismod, orci mauris cursus ligula, ut maximus arcu erat a nibh. Morbi quis mollis velit, imperdiet convallis sapien. Vivamus fringilla venenatis vulputate. Maecenas vitae magna non est tristique sodales. Pellentesque iaculis a felis accumsan tempus. Vestibulum fringilla efficitur metus, nec condimentum ipsum auctor non. Vestibulum sed orci ac augue congue porttitor a sed lorem. Sed dolor justo, ultrices in placerat at, gravida sit amet dolor.",
    page_type_id: 1,
    headline_id: 5,
    map_box_id: null,
  },
  "contact": {
    id: 6,
    title: "Contact",
    content: "Vestibulum at ligula at nunc egestas vehicula sit amet et velit. Integer varius, justo eu volutpat congue, neque ante scelerisque nulla, id volutpat sem leo in nibh. Vestibulum auctor diam a turpis fringilla feugiat. Nam lacinia convallis velit quis tincidunt. Duis vestibulum tincidunt mollis. Phasellus efficitur suscipit ultricies. Morbi quis fringilla lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, nulla sed posuere euismod, orci mauris cursus ligula, ut maximus arcu erat a nibh. Morbi quis mollis velit, imperdiet convallis sapien. Vivamus fringilla venenatis vulputate. Maecenas vitae magna non est tristique sodales. Pellentesque iaculis a felis accumsan tempus. Vestibulum fringilla efficitur metus, nec condimentum ipsum auctor non. Vestibulum sed orci ac augue congue porttitor a sed lorem. Sed dolor justo, ultrices in placerat at, gravida sit amet dolor.",
    page_type_id: 1,
    headline_id: null,
    map_box_id: 1,
  },
}
